### ISSUE TITLE
Feature request - dynamic filters

### ISSUE THREAD

**Issue by de-raaf-media** [reachweb/statamic-livewire-filters#23]
Nice plugin. It would by nice if the filters were dynamic. So if I select (in your example) "Car brand": "Audi", the filter "Special category": "Mini Van" would be disabled or invisible.

**Comment by afonic** [comment]
Hey @de-raaf-media ! Thanks a lot!

You can use the counts feature if you want to achieve this! 

If you set `enable_filter_values_count` to true, you can then access the count of each filter option by using `$this->counts[$value]` (you can see it in the default template - [for example](https://github.com/reachweb/statamic-livewire-filters/blob/master/resources/views/livewire/filters/lf-checkbox.blade.php)).

Then you can easy disable the filter using an `if`. 

I'll probably add it to the docs!

**Comment by de-raaf-media** [comment]
Oh, that's pretty cool! I'll give it a go.
