### ISSUE TITLE
Add Livewire component that can display the active filters as "pills" with option to remove

### ISSUE THREAD

**Issue by afonic** [reachweb/statamic-livewire-filters#24]

**Comment by afonic** [comment]
It's a first try but it seems to be working and all the tests pass! Lets see!

**Comment by afonic** [comment]
You should get v1.8.0, maybe you are kept back by the Statamic version?

**Comment by afonic** [comment]
I re-open this because it looks like a bug. It seems something gets passed as a parameter that shouldn't. Probably something like `as="products"` ?

Can you show me your `livewire-collection` tag and your `LfTags` tag?

**Comment by de-raaf-media** [comment]
Sure, here you go:

```
{{
  livewire-collection:products
  paginate="12" as="products"
  :blueprint:is="'product_variants_vaste-planten'"
}}

{{ livewire:lf-tags blueprint="products.product_variants_vaste-planten" fields="categorieen|bloemkleur" }}
```

**Comment by afonic** [comment]
Yeah the `as="products"` is not really needed in the tag, I will add some filters for unsupported tags.
The `:blueprint:is="'product_variants_vaste-planten'"` also needs to be fixed the same way.

It should display all the labels of the fields `categorieen|bloemkleur` correctly, do you mind sharing the filters you gave active?

**Comment by de-raaf-media** [comment]
Yeah it does show **categorieen** and **bloemkleur** so that's good. But it also shows **groenblijvend** which IS a working filter but is not a part of the fields specified in the lf-tags tag. So I would expect it to not show up as a tag.

**Comment by afonic** [comment]
Yeah you are right, I will fix this at my side.

Why are they all lowercase? If it was loading them correctly they should be `Categorieen: Siergrassen` it should take the `display` value of the field and the `title` of the tag or `label` of another field and fallback only if it cannot find them.

**Comment by afonic** [comment]
Try v1.8.1 when you have a chance.

**Comment by de-raaf-media** [comment]
Fixed! Nice! Also tags show in Title case now.

**Comment by afonic** [comment]
Good to hear!
